// AUTO-GENERATED by scripts/make-mapdata.mjs — do not edit by hand.
export default {
  "walls": [
    {
      "x": 0,
      "y": 0,
      "w": 8192,
      "h": 26,
      "type": "hedge"
    },
    {
      "x": 0,
      "y": 8166,
      "w": 8192,
      "h": 26,
      "type": "hedge"
    },
    {
      "x": 0,
      "y": 0,
      "w": 26,
      "h": 8192,
      "type": "hedge"
    },
    {
      "x": 8166,
      "y": 0,
      "w": 26,
      "h": 8192,
      "type": "hedge"
    },
    {
      "x": 4120,
      "y": 532,
      "w": 2192,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4120,
      "y": 2080,
      "w": 980,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 5280,
      "y": 2080,
      "w": 1032,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4120,
      "y": 532,
      "w": 10,
      "h": 400,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4120,
      "y": 1022,
      "w": 10,
      "h": 1058,
      "type": "fence",
      "hop": true
    },
    {
      "x": 6312,
      "y": 532,
      "w": 10,
      "h": 1548,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4320,
      "y": 584,
      "w": 1600,
      "h": 500,
      "type": "school"
    },
    {
      "x": 6120,
      "y": 584,
      "w": 180,
      "h": 480,
      "type": "school"
    },
    {
      "x": 4320,
      "y": 1184,
      "w": 800,
      "h": 240,
      "type": "school"
    },
    {
      "x": 5208,
      "y": 894,
      "w": 8,
      "h": 8,
      "type": "flag",
      "ghost": true
    },
    {
      "x": 4260,
      "y": 1064,
      "w": 46,
      "h": 12,
      "type": "rack",
      "hop": true
    },
    {
      "x": 4520,
      "y": 1564,
      "w": 8,
      "h": 8,
      "type": "swing",
      "ghost": true
    },
    {
      "x": 4740,
      "y": 1534,
      "w": 8,
      "h": 8,
      "type": "slide",
      "ghost": true
    },
    {
      "x": 5100,
      "y": 2090,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "MAPLE ELEMENTARY",
      "txt2": "Go Bulldogs!"
    },
    {
      "x": 4096,
      "y": 560,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 4096,
      "y": 900,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 4096,
      "y": 1260,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 6020,
      "y": 544,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 6020,
      "y": 1070,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 6440,
      "y": 1300,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 4320,
      "y": 2100,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 5700,
      "y": 2100,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 789,
      "y": 4932,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1670,
      "y": 2052,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 279,
      "y": 2426,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1630,
      "y": 3360,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 950,
      "y": 4651,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 640,
      "y": 3690,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1420,
      "y": 3026,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1817,
      "y": 3413,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 2245,
      "y": 3907,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 2226,
      "y": 2799,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1665,
      "y": 3450,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 752,
      "y": 4524,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 2105,
      "y": 2737,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1251,
      "y": 4218,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1810,
      "y": 3041,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1830,
      "y": 3678,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 299,
      "y": 4365,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1410,
      "y": 3111,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1937,
      "y": 3838,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 777,
      "y": 4714,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1828,
      "y": 2584,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 433,
      "y": 3035,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1023,
      "y": 3550,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 393,
      "y": 4839,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1415,
      "y": 4046,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 278,
      "y": 5610,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 632,
      "y": 4103,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 2182,
      "y": 2541,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 300,
      "y": 2140,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "WHISPERING WOODS",
      "txt2": "stay on the trail"
    },
    {
      "x": 1070,
      "y": 3040,
      "w": 140,
      "h": 200,
      "type": "treehouse"
    },
    {
      "x": 860,
      "y": 3060,
      "w": 110,
      "h": 160,
      "type": "treehouse"
    },
    {
      "x": 1090,
      "y": 3360,
      "w": 110,
      "h": 140,
      "type": "treehouse"
    },
    {
      "x": 970,
      "y": 3130,
      "w": 100,
      "h": 20,
      "type": "bridge",
      "ghost": true
    },
    {
      "x": 1115,
      "y": 3240,
      "w": 24,
      "h": 120,
      "type": "bridge",
      "ghost": true
    },
    {
      "x": 1108,
      "y": 3220,
      "w": 44,
      "h": 10,
      "type": "ladder",
      "ghost": true
    },
    {
      "x": 800,
      "y": 3040,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 960,
      "y": 2988,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1260,
      "y": 3040,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1350,
      "y": 3040,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 840,
      "y": 3300,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1420,
      "y": 3300,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 860,
      "y": 3480,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 990,
      "y": 3500,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 1260,
      "y": 3490,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 2272,
      "y": 2912,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "TREEHOUSE VILLAGE",
      "txt2": "follow the trail →"
    },
    {
      "x": 710,
      "y": 5546,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "what's up here?",
      "txt2": "a trail goes north..."
    },
    {
      "x": 710,
      "y": 3510,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "nice exploring!",
      "txt2": "back entrance to the village"
    },
    {
      "x": 2982,
      "y": 2638,
      "w": 380,
      "h": 220,
      "type": "pond",
      "noshadow": true
    },
    {
      "x": 3900,
      "y": 3200,
      "w": 56,
      "h": 30,
      "type": "table",
      "hop": true
    },
    {
      "x": 4020,
      "y": 3300,
      "w": 56,
      "h": 30,
      "type": "table",
      "hop": true
    },
    {
      "x": 2620,
      "y": 2350,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "MAPLE PARK"
    },
    {
      "x": 4000,
      "y": 3132,
      "w": 10,
      "h": 10,
      "type": "scare",
      "ghost": true
    },
    {
      "x": 3960,
      "y": 3120,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "COMMUNITY GARDEN"
    },
    {
      "x": 2600,
      "y": 2700,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 2780,
      "y": 3000,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 2600,
      "y": 3200,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 4380,
      "y": 2380,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 4380,
      "y": 3300,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 4000,
      "y": 3350,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 4390,
      "y": 2912,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "TREEHOUSE VILLAGE",
      "txt2": "follow the trail west"
    },
    {
      "x": 5730,
      "y": 2712,
      "w": 1800,
      "h": 600,
      "type": "market"
    },
    {
      "x": 7560,
      "y": 2712,
      "w": 260,
      "h": 800,
      "type": "market"
    },
    {
      "x": 5730,
      "y": 3512,
      "w": 500,
      "h": 400,
      "type": "market"
    },
    {
      "x": 6380,
      "y": 2570,
      "w": 26,
      "h": 20,
      "type": "cart",
      "hop": true
    },
    {
      "x": 6440,
      "y": 2600,
      "w": 26,
      "h": 20,
      "type": "cart",
      "hop": true
    },
    {
      "x": 6280,
      "y": 4372,
      "w": 10,
      "h": 10,
      "type": "cone",
      "ghost": true
    },
    {
      "x": 7480,
      "y": 4372,
      "w": 10,
      "h": 10,
      "type": "cone",
      "ghost": true
    },
    {
      "x": 6300,
      "y": 4442,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "MAPLE MART DISTRICT",
      "txt2": "open daily 8am–8pm"
    },
    {
      "x": 6680,
      "y": 2612,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "E-BIKE GRAND PRIX",
      "txt2": "saturday · starts here"
    },
    {
      "x": 5710,
      "y": 4200,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 7780,
      "y": 3576,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 7280,
      "y": 4100,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 2640,
      "y": 3640,
      "w": 215,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2945,
      "y": 3640,
      "w": 215,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2640,
      "y": 4110,
      "w": 520,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2640,
      "y": 3640,
      "w": 10,
      "h": 216,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2640,
      "y": 3932,
      "w": 10,
      "h": 188,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3150,
      "y": 3640,
      "w": 10,
      "h": 216,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3150,
      "y": 3932,
      "w": 10,
      "h": 188,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2775,
      "y": 3860,
      "w": 250,
      "h": 170,
      "type": "house",
      "hue": "#6b4a76",
      "trim": "#ffe9c2"
    },
    {
      "x": 2676,
      "y": 4010,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 3033,
      "y": 3990,
      "w": 24,
      "h": 24,
      "type": "trash",
      "hop": true
    },
    {
      "x": 2953,
      "y": 3634,
      "w": 10,
      "h": 12,
      "type": "mailbox",
      "ghost": true
    },
    {
      "x": 4640,
      "y": 3640,
      "w": 215,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4945,
      "y": 3640,
      "w": 215,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4640,
      "y": 4110,
      "w": 520,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4640,
      "y": 3640,
      "w": 10,
      "h": 216,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4640,
      "y": 3932,
      "w": 10,
      "h": 188,
      "type": "fence",
      "hop": true
    },
    {
      "x": 5150,
      "y": 3640,
      "w": 10,
      "h": 216,
      "type": "fence",
      "hop": true
    },
    {
      "x": 5150,
      "y": 3932,
      "w": 10,
      "h": 188,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4775,
      "y": 3860,
      "w": 250,
      "h": 170,
      "type": "house",
      "hue": "#5c6f9e",
      "trim": "#ffe9c2"
    },
    {
      "x": 5033,
      "y": 3990,
      "w": 24,
      "h": 24,
      "type": "trash",
      "hop": true
    },
    {
      "x": 4953,
      "y": 3634,
      "w": 10,
      "h": 12,
      "type": "mailbox",
      "ghost": true
    },
    {
      "x": 4720,
      "y": 4000,
      "w": 8,
      "h": 8,
      "type": "hoop",
      "ghost": true
    },
    {
      "x": 4640,
      "y": 4660,
      "w": 185,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4915,
      "y": 4660,
      "w": 185,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4640,
      "y": 4890,
      "w": 460,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4640,
      "y": 4660,
      "w": 10,
      "h": 108,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4640,
      "y": 4844,
      "w": 10,
      "h": 56,
      "type": "fence",
      "hop": true
    },
    {
      "x": 5090,
      "y": 4660,
      "w": 10,
      "h": 108,
      "type": "fence",
      "hop": true
    },
    {
      "x": 5090,
      "y": 4844,
      "w": 10,
      "h": 56,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4745,
      "y": 4670,
      "w": 250,
      "h": 150,
      "type": "house",
      "hue": "#4f6b5e",
      "trim": "#ffe9c2"
    },
    {
      "x": 5003,
      "y": 4780,
      "w": 24,
      "h": 24,
      "type": "trash",
      "hop": true
    },
    {
      "x": 4923,
      "y": 4654,
      "w": 10,
      "h": 12,
      "type": "mailbox",
      "ghost": true
    },
    {
      "x": 2900,
      "y": 4640,
      "w": 300,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3300,
      "y": 4640,
      "w": 360,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2900,
      "y": 4940,
      "w": 760,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2900,
      "y": 4640,
      "w": 10,
      "h": 140,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2900,
      "y": 4856,
      "w": 10,
      "h": 84,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3660,
      "y": 4640,
      "w": 10,
      "h": 140,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3660,
      "y": 4856,
      "w": 10,
      "h": 84,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3060,
      "y": 4700,
      "w": 260,
      "h": 180,
      "type": "house",
      "hue": "#8a6f3e",
      "trim": "#ffe9c2"
    },
    {
      "x": 3480,
      "y": 4760,
      "w": 60,
      "h": 50,
      "type": "doghouse",
      "ghost": true
    },
    {
      "x": 2940,
      "y": 4650,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "BEWARE OF DOG",
      "txt2": "(his name is Biscuit)"
    },
    {
      "x": 3720,
      "y": 4680,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 3820,
      "y": 4820,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 3760,
      "y": 5630,
      "w": 170,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4020,
      "y": 5630,
      "w": 180,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3760,
      "y": 5980,
      "w": 440,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3760,
      "y": 5630,
      "w": 10,
      "h": 162,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3760,
      "y": 5868,
      "w": 10,
      "h": 122,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4190,
      "y": 5630,
      "w": 10,
      "h": 162,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4190,
      "y": 5868,
      "w": 10,
      "h": 122,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3855,
      "y": 5730,
      "w": 250,
      "h": 170,
      "type": "house",
      "player": true,
      "hue": "#2e8f8a",
      "trim": "#ffc44d"
    },
    {
      "x": 3740,
      "y": 5880,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 4113,
      "y": 5860,
      "w": 24,
      "h": 24,
      "type": "trash",
      "hop": true
    },
    {
      "x": 4028,
      "y": 5624,
      "w": 10,
      "h": 12,
      "type": "mailbox",
      "ghost": true
    },
    {
      "x": 2580,
      "y": 4100,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 5060,
      "y": 4125,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 2580,
      "y": 5500,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 5070,
      "y": 5000,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 6520,
      "y": 6310,
      "w": 260,
      "h": 140,
      "type": "shack"
    },
    {
      "x": 2560,
      "y": 6490,
      "w": 1836,
      "h": 26,
      "type": "water"
    },
    {
      "x": 4564,
      "y": 6490,
      "w": 3372,
      "h": 26,
      "type": "water"
    },
    {
      "x": 4396,
      "y": 6490,
      "w": 168,
      "h": 280,
      "type": "dock",
      "ghost": true
    },
    {
      "x": 4410,
      "y": 6560,
      "w": 48,
      "h": 36,
      "type": "paddleboat",
      "ghost": true,
      "hue": "#57b8ff"
    },
    {
      "x": 4492,
      "y": 6630,
      "w": 48,
      "h": 36,
      "type": "paddleboat",
      "ghost": true,
      "hue": "#ff8f57"
    },
    {
      "x": 3000,
      "y": 6422,
      "w": 60,
      "h": 4,
      "type": "umbrella",
      "ghost": true,
      "hue": "#ff6b57"
    },
    {
      "x": 3600,
      "y": 6422,
      "w": 60,
      "h": 4,
      "type": "umbrella",
      "ghost": true,
      "hue": "#ffc44d"
    },
    {
      "x": 4800,
      "y": 6422,
      "w": 60,
      "h": 4,
      "type": "umbrella",
      "ghost": true,
      "hue": "#2ec4b6"
    },
    {
      "x": 5300,
      "y": 6422,
      "w": 60,
      "h": 4,
      "type": "umbrella",
      "ghost": true,
      "hue": "#ff9ac1"
    },
    {
      "x": 5900,
      "y": 6422,
      "w": 60,
      "h": 4,
      "type": "umbrella",
      "ghost": true,
      "hue": "#9ad17f"
    },
    {
      "x": 3060,
      "y": 6330,
      "w": 120,
      "h": 80,
      "type": "truck",
      "ghost": true
    },
    {
      "x": 2650,
      "y": 6410,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "GREAT WATERFRONT LAKE",
      "txt2": "no swimming beyond the dock"
    },
    {
      "x": 4396,
      "y": 6462,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "DOCK",
      "txt2": "watch your step"
    },
    {
      "x": 2600,
      "y": 6390,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 7840,
      "y": 6390,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 512,
      "y": 512,
      "w": 1536,
      "h": 26,
      "type": "hedge",
      "hop": true
    },
    {
      "x": 512,
      "y": 1766,
      "w": 1536,
      "h": 26,
      "type": "hedge",
      "hop": true
    },
    {
      "x": 512,
      "y": 512,
      "w": 26,
      "h": 1280,
      "type": "hedge",
      "hop": true
    },
    {
      "x": 2022,
      "y": 512,
      "w": 26,
      "h": 1280,
      "type": "hedge",
      "hop": true
    },
    {
      "x": 2060,
      "y": 1780,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "DANGER",
      "txt2": "CONSTRUCTION ZONE"
    },
    {
      "x": 540,
      "y": 560,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "HARD HAT",
      "txt2": "area required"
    },
    {
      "x": 1890,
      "y": 560,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "AUTHORIZED",
      "txt2": "personnel only"
    },
    {
      "x": 680,
      "y": 1759,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "KEEP OUT",
      "txt2": "seriously"
    },
    {
      "x": 1400,
      "y": 1759,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "NO TRESPASSING",
      "txt2": "city ordinance 7-41"
    },
    {
      "x": 630,
      "y": 545,
      "w": 10,
      "h": 10,
      "type": "cone",
      "ghost": true
    },
    {
      "x": 1520,
      "y": 545,
      "w": 10,
      "h": 10,
      "type": "cone",
      "ghost": true
    },
    {
      "x": 534,
      "y": 700,
      "w": 10,
      "h": 10,
      "type": "cone",
      "ghost": true
    },
    {
      "x": 534,
      "y": 1560,
      "w": 10,
      "h": 10,
      "type": "cone",
      "ghost": true
    },
    {
      "x": 2010,
      "y": 700,
      "w": 10,
      "h": 10,
      "type": "cone",
      "ghost": true
    },
    {
      "x": 2010,
      "y": 1380,
      "w": 10,
      "h": 10,
      "type": "cone",
      "ghost": true
    },
    {
      "x": 555,
      "y": 605,
      "w": 230,
      "h": 150,
      "type": "dozer"
    },
    {
      "x": 900,
      "y": 600,
      "w": 326,
      "h": 14,
      "type": "frame"
    },
    {
      "x": 900,
      "y": 600,
      "w": 14,
      "h": 310,
      "type": "frame"
    },
    {
      "x": 1212,
      "y": 600,
      "w": 14,
      "h": 310,
      "type": "frame"
    },
    {
      "x": 1000,
      "y": 626,
      "w": 122,
      "h": 84,
      "type": "scaffold",
      "hop": true
    },
    {
      "x": 1460,
      "y": 850,
      "w": 280,
      "h": 14,
      "type": "frame"
    },
    {
      "x": 1460,
      "y": 850,
      "w": 14,
      "h": 310,
      "type": "frame"
    },
    {
      "x": 1726,
      "y": 850,
      "w": 14,
      "h": 310,
      "type": "frame"
    },
    {
      "x": 1460,
      "y": 1146,
      "w": 140,
      "h": 14,
      "type": "frame"
    },
    {
      "x": 1740,
      "y": 550,
      "w": 200,
      "h": 96,
      "type": "pipe"
    },
    {
      "x": 1762,
      "y": 666,
      "w": 158,
      "h": 74,
      "type": "pipe"
    },
    {
      "x": 716,
      "y": 866,
      "w": 134,
      "h": 84,
      "type": "mound"
    },
    {
      "x": 1642,
      "y": 650,
      "w": 102,
      "h": 72,
      "type": "mound"
    },
    {
      "x": 876,
      "y": 1540,
      "w": 152,
      "h": 92,
      "type": "mound"
    },
    {
      "x": 1382,
      "y": 1558,
      "w": 132,
      "h": 82,
      "type": "mound"
    },
    {
      "x": 638,
      "y": 1368,
      "w": 224,
      "h": 62,
      "type": "ramp",
      "hop": true
    },
    {
      "x": 916,
      "y": 1308,
      "w": 62,
      "h": 224,
      "type": "ramp",
      "hop": true
    },
    {
      "x": 1682,
      "y": 1378,
      "w": 202,
      "h": 82,
      "type": "rack",
      "hop": true
    },
    {
      "x": 1600,
      "y": 1480,
      "w": 182,
      "h": 62,
      "type": "table",
      "hop": true
    },
    {
      "x": 6336,
      "y": 1024,
      "w": 380,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 7256,
      "y": 1024,
      "w": 104,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 6336,
      "y": 2102,
      "w": 1024,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 7330,
      "y": 1024,
      "w": 10,
      "h": 1078,
      "type": "fence",
      "hop": true
    },
    {
      "x": 6336,
      "y": 1024,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "ATHLETIC FIELDS",
      "txt2": "all athletes welcome"
    },
    {
      "x": 6538,
      "y": 1034,
      "w": 120,
      "h": 54,
      "type": "goal"
    },
    {
      "x": 6538,
      "y": 2040,
      "w": 120,
      "h": 54,
      "type": "goal"
    },
    {
      "x": 6998,
      "y": 1578,
      "w": 124,
      "h": 42,
      "type": "backstop"
    },
    {
      "x": 7270,
      "y": 1062,
      "w": 60,
      "h": 458,
      "type": "bleacher",
      "hop": true
    },
    {
      "x": 6862,
      "y": 1952,
      "w": 42,
      "h": 42,
      "type": "fountain",
      "ghost": true
    },
    {
      "x": 6680,
      "y": 530,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 6760,
      "y": 610,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 6710,
      "y": 684,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 7490,
      "y": 542,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 7562,
      "y": 626,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 7522,
      "y": 714,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 7160,
      "y": 660,
      "w": 120,
      "h": 80,
      "type": "watertower"
    },
    {
      "x": 7000,
      "y": 1000,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "WATER TOWER TRAIL",
      "txt2": "↑ follow the path"
    },
    {
      "x": 300,
      "y": 5950,
      "w": 12,
      "h": 14,
      "type": "sign",
      "ghost": true,
      "txt": "MEADOW RESERVE",
      "txt2": "future development"
    },
    {
      "x": 2640,
      "y": 5400,
      "w": 215,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2945,
      "y": 5400,
      "w": 215,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2640,
      "y": 5602,
      "w": 520,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2640,
      "y": 5400,
      "w": 10,
      "h": 85,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2640,
      "y": 5561,
      "w": 10,
      "h": 29,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3150,
      "y": 5400,
      "w": 10,
      "h": 85,
      "type": "fence",
      "hop": true
    },
    {
      "x": 3150,
      "y": 5561,
      "w": 10,
      "h": 29,
      "type": "fence",
      "hop": true
    },
    {
      "x": 2775,
      "y": 5430,
      "w": 250,
      "h": 130,
      "type": "house",
      "hue": "#56406f",
      "trim": "#ffe9c2"
    },
    {
      "x": 2676,
      "y": 5540,
      "w": 20,
      "h": 20,
      "type": "tree"
    },
    {
      "x": 3033,
      "y": 5510,
      "w": 24,
      "h": 24,
      "type": "trash",
      "hop": true
    },
    {
      "x": 2953,
      "y": 5394,
      "w": 10,
      "h": 12,
      "type": "mailbox",
      "ghost": true
    },
    {
      "x": 4640,
      "y": 5400,
      "w": 215,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4945,
      "y": 5400,
      "w": 215,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4640,
      "y": 5602,
      "w": 520,
      "h": 10,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4640,
      "y": 5400,
      "w": 10,
      "h": 85,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4640,
      "y": 5561,
      "w": 10,
      "h": 29,
      "type": "fence",
      "hop": true
    },
    {
      "x": 5150,
      "y": 5400,
      "w": 10,
      "h": 85,
      "type": "fence",
      "hop": true
    },
    {
      "x": 5150,
      "y": 5561,
      "w": 10,
      "h": 29,
      "type": "fence",
      "hop": true
    },
    {
      "x": 4775,
      "y": 5430,
      "w": 250,
      "h": 130,
      "type": "house",
      "hue": "#7a5560",
      "trim": "#ffe9c2"
    },
    {
      "x": 5033,
      "y": 5510,
      "w": 24,
      "h": 24,
      "type": "trash",
      "hop": true
    },
    {
      "x": 4953,
      "y": 5394,
      "w": 10,
      "h": 12,
      "type": "mailbox",
      "ghost": true
    }
  ],
  "canopies": [
    {
      "x": 4106,
      "y": 564,
      "r": 56
    },
    {
      "x": 4106,
      "y": 904,
      "r": 60
    },
    {
      "x": 4106,
      "y": 1264,
      "r": 52
    },
    {
      "x": 6030,
      "y": 548,
      "r": 56
    },
    {
      "x": 6030,
      "y": 1074,
      "r": 60
    },
    {
      "x": 6450,
      "y": 1304,
      "r": 52
    },
    {
      "x": 4330,
      "y": 2104,
      "r": 54
    },
    {
      "x": 5710,
      "y": 2104,
      "r": 54
    },
    {
      "x": 799,
      "y": 4936,
      "r": 59
    },
    {
      "x": 1680,
      "y": 2056,
      "r": 66
    },
    {
      "x": 289,
      "y": 2430,
      "r": 56
    },
    {
      "x": 1640,
      "y": 3364,
      "r": 48
    },
    {
      "x": 960,
      "y": 4655,
      "r": 52
    },
    {
      "x": 650,
      "y": 3694,
      "r": 64
    },
    {
      "x": 1430,
      "y": 3030,
      "r": 59
    },
    {
      "x": 1827,
      "y": 3417,
      "r": 65
    },
    {
      "x": 2255,
      "y": 3911,
      "r": 52
    },
    {
      "x": 2236,
      "y": 2803,
      "r": 57
    },
    {
      "x": 1675,
      "y": 3454,
      "r": 53
    },
    {
      "x": 762,
      "y": 4528,
      "r": 55
    },
    {
      "x": 2115,
      "y": 2741,
      "r": 66
    },
    {
      "x": 1261,
      "y": 4222,
      "r": 63
    },
    {
      "x": 1820,
      "y": 3045,
      "r": 60
    },
    {
      "x": 1840,
      "y": 3682,
      "r": 50
    },
    {
      "x": 309,
      "y": 4369,
      "r": 70
    },
    {
      "x": 1420,
      "y": 3115,
      "r": 63
    },
    {
      "x": 1947,
      "y": 3842,
      "r": 63
    },
    {
      "x": 787,
      "y": 4718,
      "r": 61
    },
    {
      "x": 1838,
      "y": 2588,
      "r": 64
    },
    {
      "x": 443,
      "y": 3039,
      "r": 61
    },
    {
      "x": 1033,
      "y": 3554,
      "r": 66
    },
    {
      "x": 403,
      "y": 4843,
      "r": 47
    },
    {
      "x": 1425,
      "y": 4050,
      "r": 63
    },
    {
      "x": 288,
      "y": 5614,
      "r": 66
    },
    {
      "x": 642,
      "y": 4107,
      "r": 65
    },
    {
      "x": 2192,
      "y": 2545,
      "r": 48
    },
    {
      "x": 810,
      "y": 3044,
      "r": 44
    },
    {
      "x": 970,
      "y": 2992,
      "r": 48
    },
    {
      "x": 1270,
      "y": 3044,
      "r": 46
    },
    {
      "x": 1360,
      "y": 3044,
      "r": 50
    },
    {
      "x": 850,
      "y": 3304,
      "r": 46
    },
    {
      "x": 1430,
      "y": 3304,
      "r": 50
    },
    {
      "x": 870,
      "y": 3484,
      "r": 44
    },
    {
      "x": 1000,
      "y": 3504,
      "r": 46
    },
    {
      "x": 1270,
      "y": 3494,
      "r": 48
    },
    {
      "x": 2610,
      "y": 2704,
      "r": 58
    },
    {
      "x": 2790,
      "y": 3004,
      "r": 54
    },
    {
      "x": 2610,
      "y": 3204,
      "r": 56
    },
    {
      "x": 4390,
      "y": 2384,
      "r": 52
    },
    {
      "x": 4390,
      "y": 3304,
      "r": 56
    },
    {
      "x": 4010,
      "y": 3354,
      "r": 52
    },
    {
      "x": 5720,
      "y": 4204,
      "r": 56
    },
    {
      "x": 7790,
      "y": 3580,
      "r": 60
    },
    {
      "x": 7290,
      "y": 4104,
      "r": 52
    },
    {
      "x": 2686,
      "y": 4014,
      "r": 52
    },
    {
      "x": 3730,
      "y": 4684,
      "r": 56
    },
    {
      "x": 3830,
      "y": 4824,
      "r": 50
    },
    {
      "x": 3750,
      "y": 5884,
      "r": 52
    },
    {
      "x": 2590,
      "y": 4104,
      "r": 52
    },
    {
      "x": 5070,
      "y": 4129,
      "r": 54
    },
    {
      "x": 2590,
      "y": 5504,
      "r": 54
    },
    {
      "x": 5080,
      "y": 5004,
      "r": 52
    },
    {
      "x": 2610,
      "y": 6394,
      "r": 52
    },
    {
      "x": 7850,
      "y": 6394,
      "r": 52
    },
    {
      "x": 6690,
      "y": 534,
      "r": 50
    },
    {
      "x": 6770,
      "y": 614,
      "r": 46
    },
    {
      "x": 6720,
      "y": 688,
      "r": 44
    },
    {
      "x": 7500,
      "y": 546,
      "r": 52
    },
    {
      "x": 7572,
      "y": 630,
      "r": 48
    },
    {
      "x": 7532,
      "y": 718,
      "r": 44
    },
    {
      "x": 2686,
      "y": 5544,
      "r": 52
    }
  ],
  "lamps": [
    {
      "x": 5200,
      "y": 900
    },
    {
      "x": 5200,
      "y": 1800
    },
    {
      "x": 4600,
      "y": 900
    },
    {
      "x": 5800,
      "y": 900
    },
    {
      "x": 340,
      "y": 2220
    },
    {
      "x": 340,
      "y": 3800
    },
    {
      "x": 340,
      "y": 5200
    },
    {
      "x": 1000,
      "y": 3160
    },
    {
      "x": 1260,
      "y": 3420
    },
    {
      "x": 3200,
      "y": 2400
    },
    {
      "x": 4100,
      "y": 3300
    },
    {
      "x": 4380,
      "y": 2920
    },
    {
      "x": 3500,
      "y": 2920
    },
    {
      "x": 2600,
      "y": 2920
    },
    {
      "x": 5900,
      "y": 2750
    },
    {
      "x": 6700,
      "y": 4000
    },
    {
      "x": 7500,
      "y": 3100
    },
    {
      "x": 4418,
      "y": 3700
    },
    {
      "x": 4618,
      "y": 4100
    },
    {
      "x": 4418,
      "y": 4630
    },
    {
      "x": 4618,
      "y": 4900
    },
    {
      "x": 4418,
      "y": 5395
    },
    {
      "x": 4618,
      "y": 5700
    },
    {
      "x": 4418,
      "y": 4460
    },
    {
      "x": 4618,
      "y": 4460
    },
    {
      "x": 4418,
      "y": 5228
    },
    {
      "x": 4618,
      "y": 5228
    },
    {
      "x": 3100,
      "y": 6465
    },
    {
      "x": 5000,
      "y": 6465
    },
    {
      "x": 6560,
      "y": 6465
    },
    {
      "x": 1280,
      "y": 640
    },
    {
      "x": 790,
      "y": 1250
    },
    {
      "x": 6380,
      "y": 1080
    },
    {
      "x": 6820,
      "y": 1080
    },
    {
      "x": 7060,
      "y": 1080
    },
    {
      "x": 7060,
      "y": 2080
    },
    {
      "x": 6380,
      "y": 2080
    },
    {
      "x": 6820,
      "y": 2080
    },
    {
      "x": 7220,
      "y": 842
    },
    {
      "x": 7052,
      "y": 932
    }
  ],
  "doors": [
    {
      "x": 3923,
      "y": 5888,
      "w": 64,
      "h": 22,
      "target": "house",
      "spawnX": 240,
      "spawnY": 200,
      "worldReturn": {
        "x": 3955,
        "y": 5932
      }
    },
    {
      "x": 6598,
      "y": 3300,
      "w": 80,
      "h": 22,
      "target": "mart",
      "spawnX": 320,
      "spawnY": 340,
      "worldReturn": {
        "x": 6640,
        "y": 3355
      }
    },
    {
      "x": 5088,
      "y": 1072,
      "w": 100,
      "h": 22,
      "worldReturn": {
        "x": 5138,
        "y": 1106
      },
      "txt": "School's out for summer!"
    },
    {
      "x": 4688,
      "y": 1412,
      "w": 80,
      "h": 22,
      "worldReturn": {
        "x": 4728,
        "y": 1444
      },
      "txt": "Gym's closed for the summer."
    },
    {
      "x": 2708,
      "y": 4018,
      "w": 50,
      "h": 22,
      "worldReturn": {
        "x": 2733,
        "y": 4040
      },
      "txt": "Nobody home right now."
    },
    {
      "x": 4843,
      "y": 4018,
      "w": 50,
      "h": 22,
      "worldReturn": {
        "x": 4868,
        "y": 4040
      },
      "txt": "Back in a bit!"
    },
    {
      "x": 4813,
      "y": 4798,
      "w": 50,
      "h": 22,
      "worldReturn": {
        "x": 4838,
        "y": 4832
      },
      "txt": "Shh — baby napping."
    },
    {
      "x": 2708,
      "y": 5548,
      "w": 50,
      "h": 22,
      "worldReturn": {
        "x": 2733,
        "y": 5572
      },
      "txt": "Ring the bell?"
    },
    {
      "x": 4843,
      "y": 5548,
      "w": 50,
      "h": 22,
      "worldReturn": {
        "x": 4868,
        "y": 5572
      },
      "txt": "Gone fishing."
    },
    {
      "x": 6618,
      "y": 6438,
      "w": 64,
      "h": 22,
      "target": "snackshack",
      "spawnX": 160,
      "spawnY": 185,
      "worldReturn": {
        "x": 6650,
        "y": 6472
      }
    },
    {
      "x": 1100,
      "y": 3225,
      "w": 60,
      "h": 22,
      "target": "treehouse_hq",
      "spawnX": 240,
      "spawnY": 150,
      "worldReturn": {
        "x": 1140,
        "y": 3262
      }
    }
  ]
};
