/**
 * One-time script: patches mapdata.js to fix every issue found by validate-map.js.
 * Run once, then delete this file (or keep for reference).
 *
 * node scripts/fix-mapdata.mjs
 */
import { readFileSync, writeFileSync } from 'fs';

const jsText  = readFileSync('./src/world/mapdata.js', 'utf8');
const jsonText = jsText.replace(/^[\s\S]*?export default /, '').replace(/;\s*$/, '');
const data    = JSON.parse(jsonText);
const { walls: ws, canopies: cs } = data;

// ── helpers ────────────────────────────────────────────────────────────
function findW(type, x, y) {
  const w = ws.find(w => w.type === type && w.x === x && w.y === y);
  if (!w) throw new Error(`wall ${type}@(${x},${y}) not found`);
  return w;
}
function findC(x, y) {
  const c = cs.find(c => c.x === x && c.y === y);
  if (!c) throw new Error(`canopy@(${x},${y}) not found`);
  return c;
}

// ── CHECK A: park trees in main road (x=4448..4588) ───────────────────
// Move 28px west — trunk clears road; canopy is visual-only, no collision.
{
  const t = findW('tree', 4440, 2380); t.x = 4420;
  const c = findC(4450, 2384);         c.x = 4430;
}
{
  const t = findW('tree', 4500, 3300); t.x = 4420;
  const c = findC(4510, 3304);         c.x = 4430;
}

// ── CHECK B: Athletic — goals overlapping perimeter fence ─────────────
// North goal: move 8px south to clear fence bottom (y=1024+10=1034)
{ const g = findW('goal', 6538, 1026); g.y = 1034; }
// South goal: move 20px north to clear fence top (y=2102)
{ const g = findW('goal', 6538, 2060); g.y = 2040; }

// ── CHECK B: Athletic — bleacher overlapping east fence ───────────────
// Bleacher right edge was 8px inside fence; shift 8px west
{ const b = findW('bleacher', 7278, 1062); b.x = 7270; }

// ── CHECK B: Construction — mound overlapping ramp ────────────────────
// Ramp at (916,1308,62,224) bottom=1532; move mound south of ramp bottom
{ const m = findW('mound', 876, 1490); m.y = 1540; }

// ── CHECK B: Neighbourhood — NE-yard corner tree touching south fence ──
// South fence at y=4110..4120; move tree 25px south so it clears the fence
{
  const t = findW('tree', 5060, 4100); t.y = 4125;
  const c = findC(5070, 4104);         c.y = 4129;
}

// ── CHECK B: School — bike rack overlapping school building ───────────
// Rack right edge was 6px inside school left wall (x=4320); shift 50px east
{ const r = findW('rack', 4280, 1064); r.x = 4330; }

// ── CHECK B: Shopping — tree inside market east wing ──────────────────
// Market east wing: x=7560..7820, y=2712..3512.  Move tree south of wing.
{
  const t = findW('tree', 7780, 3100); t.y = 3520;
  const c = findC(7790, 3104);         c.y = 3524;
}

// ── CHECK C: school-west trees outside any region ─────────────────────
// Gap between Construction (east=2048) and School (west=4096).
// Move trees to x=4096 (just inside school region left edge).
for (const [ox, oy, cx_old, cy_old] of [
  [3980, 560,  3990, 564],
  [3880, 900,  3890, 904],
  [3940, 1260, 3950, 1264],
]) {
  const t = findW('tree', ox, oy); t.x = 4096;
  const c = findC(cx_old, cy_old); c.x = 4106;
}

// ── CHECK C: school-east trees outside any region ─────────────────────
// Gap east of School (right=6336) before Athletic/WaterTower.
// Move trees to x=6300 (inside school right edge).
for (const [ox, oy, cx_old, cy_old] of [
  [6400, 540,  6410, 544],
  [6560, 940,  6570, 944],
]) {
  const t = findW('tree', ox, oy); t.x = 6300;
  const c = findC(cx_old, cy_old); c.x = 6310;
}

// ── CHECK C: woods tree south of woods region bottom (y=5632) ─────────
// Tree centre was at y=5636; move 16px north.
{
  const t = findW('tree', 278, 5626); t.y = 5610;
  const c = findC(288, 5630);        c.y = 5614;
}

// ── CHECK C: shopping carts above shopping region top (y=2560) ────────
// Carts were in the undefined gap above the shopping district.
// Move them into the shopping region (y≥2560), south of the road spur.
{ const c = ws.find(w => w.type === 'cart' && w.x === 6380 && w.y === 2312);
  if (!c) throw new Error('cart@(6380,2312) not found'); c.y = 2570; }
{ const c = ws.find(w => w.type === 'cart' && w.x === 6440 && w.y === 2352);
  if (!c) throw new Error('cart@(6440,2352) not found'); c.y = 2600; }

// ── CHECK B: Woods — two seeded trees overlapping each other ──────────
// (1263,3026) landed on top of treehouse perimeter tree (1260,3040).
// Move the seeded tree 33px west, clear of the perimeter tree.
{
  const t = findW('tree', 1263, 3026); t.x = 1230;
  const c = findC(1273, 3030);        c.x = 1240;
}

// ── Write output ──────────────────────────────────────────────────────
const header = '// AUTO-GENERATED by scripts/make-mapdata.mjs — do not edit by hand.\n';
writeFileSync('./src/world/mapdata.js',
  header + 'export default ' + JSON.stringify(data, null, 2) + ';\n');
console.log('Patched src/world/mapdata.js — 18 fixes applied.');
